# Generated by Django 5.0.6 on 2024-06-20 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("debate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArgumentativeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="An identifier that is a hash of: ``slugify(self.statement.statement[self.start:self.end])+self.statement.identifier. It's created when the model is saved.",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "start",
                    models.PositiveIntegerField(
                        help_text="The start of the argumentative component in the statement"
                    ),
                ),
                (
                    "end",
                    models.PositiveIntegerField(
                        help_text="The end of the argumentative component in the statement"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[("CL", "Claim"), ("PR", "Premise")],
                        help_text="The label for this argumentative component.",
                        max_length=2,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Score (between 0 and 1) given by an automatic model to the classification label. It's useful to get a general idea how certain is the model about a prediction.",
                        null=True,
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        help_text="Position statement this is an Argumentative Component of",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="argumentative_components",
                        to="debate.statement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArgumentativeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[("ATT", "Attack"), ("SUP", "Support")],
                        help_text="The type of relation between the components.",
                        max_length=3,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Score (between 0 and 1) given by an automatic model to the classification label. It's useful to get a general idea how certain is the model about a prediction.",
                        null=True,
                    ),
                ),
                (
                    "component_from",
                    models.ForeignKey(
                        help_text="The argumentative component that is the start of the relation. I.e., 'A' in 'A'->'B'.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_relations",
                        to="argmining.argumentativecomponent",
                    ),
                ),
                (
                    "component_to",
                    models.ForeignKey(
                        help_text="The argumentative component that is the end of the relation. I.e., 'B' in 'A'->'B'.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_relations",
                        to="argmining.argumentativecomponent",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="argumentativerelation",
            constraint=models.UniqueConstraint(
                fields=("component_from", "component_to"), name="unique_edge"
            ),
        ),
    ]
