# Generated by Django 5.0.6 on 2024-07-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("argmining", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="argumentativecomponent",
            name="has_manual_annotation",
            field=models.BooleanField(
                default=False,
                help_text="Boolean value to denote that the component was annotated manually",
            ),
        ),
        migrations.AddField(
            model_name="argumentativerelation",
            name="has_manual_annotation",
            field=models.BooleanField(
                default=False,
                help_text="Boolean value to denote that the relation was annotated manually",
            ),
        ),
    ]
