# Generated by Django 5.0.6 on 2024-07-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="has_manual_annotation",
            field=models.BooleanField(
                default=False,
                help_text="Boolean value to denote that the statement was annotated manually",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="statement_classification_score",
            field=models.FloatField(
                blank=True,
                help_text="Score (between 0 and 1) given by an automatic model for statement classification. It's useful to get a general idea how certain is the model about a prediction.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="statement_relation_score",
            field=models.FloatField(
                blank=True,
                help_text="Score (between 0 and 1) given by an automatic model for statement relation. It's useful to get a general idea how certain is the model about a prediction.",
                null=True,
            ),
        ),
    ]
